disable CONFIG_SCSI_UFSHCD to avoid Linux-Next BUILD_BUG_ON failed of ufshcd.o
since next-20230801, there are following compile error for drivers/ufs/core/ufshcd.c
error: call to ‘__compiletime_assert_598’ declared with attribute error: BUILD_BUG_ON failed: ((u8 *)&(struct request_desc_header){ .enable_crypto = 1})[2] != 0x80

disable UFS to bypass such issue since it's not needed on SPR or similar TDX guest test setup

Signed-off-by: Hongyu, Ning <hongyu.ning@intel.com>